/// <reference path="../typings/tsd.d.ts" />
/// <reference path="models/Song.ts" />
/// <reference path="filters/filters.ts"/>
/// <reference path="directives/license.ts"/>
/// <reference path="directives/licensetype.ts"/>
/// <reference path="directives/status.ts"/>
/// <reference path="directives/yesno.ts"/>
/// <reference path="controller/SongAddController.ts"/>
/// <reference path="controller/SongDetailController.ts"/>
/// <reference path="controller/SongListController.ts"/>
/// <reference path="app.ts"/>
