CREATE TABLE `songs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `text` longtext,
  `alternativeTitles` varchar(1000) DEFAULT '',
  `interpret` varchar(255) DEFAULT NULL,
  `pageRondoRed` int(11) DEFAULT NULL,
  `pageRondoBlue` int(11) DEFAULT NULL,
  `pageRondoGreen` int(11) DEFAULT NULL,
  `pageRondo2017` int(11) DEFAULT NULL,
  `releaseApp2017` tinyint(1) NOT NULL DEFAULT '1',
  `releaseBook2017` tinyint(1) NOT NULL DEFAULT '0',
  `releaseBook2021` tinyint(1) NOT NULL DEFAULT '1',
  `copyrightInfoApp` text,
  `copyrightInfoBook` text,
  `copyrightContact` varchar(1000) DEFAULT '',
  `copyrightStatusApp` enum('NEW','INPROGRESS','DONE','NO_LICENSE') NOT NULL DEFAULT 'NEW',
  `copyrightStatusBook2017` enum('NEW','INPROGRESS','DONE','NO_LICENSE') NOT NULL DEFAULT 'NEW',
  `copyrightStatusBook2021` enum('NEW','INPROGRESS','DONE','NO_LICENSE') NOT NULL DEFAULT 'NEW',
  `license` enum('UNKNOWN','FREE','LICENSED') NOT NULL DEFAULT 'UNKNOWN',
  `license_type` enum('UNKNOWN','ONE_TIME','ANNUAL','FREE') NOT NULL DEFAULT 'UNKNOWN',
  `comments` text,
  `status` enum('NEW','INPROGRESS','DONE') NOT NULL DEFAULT 'NEW',
  `updated` int(11) DEFAULT NULL,
  `rawImage` longblob,
  `rawXML` longblob,
  `rawSIB` longblob,
  `rawNotesPDF` longblob,
  `rawNotesPNG` longblob,
  `rawMidi` longblob,
  `rawCopyrightPDF` longblob,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
